
name: TimedOut

on:
  workflow_dispatch:
    inputs:
      condition:
        description: 'Always timed out.'
        required: true
        type: boolean
        default: false

jobs:
  conditional:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 25200
      - name: true
        if: ${{ github.event.inputs.condition == 'true' }}
        run: exit 0
      - name: false
        if: ${{ github.event.inputs.condition == 'false' }}
        run: exit 1